#!/bin/sh
/usr/bin/docker run --net=host --rm -v /opt/pidalio/kube/kubelet/scripts/ceph/resolv.conf:/etc/resolv.conf:ro -v /opt/pidalio/kube/kubelet/scripts/ceph/keys/:/etc/ceph cloudwattfr/pidalio:ceph-base rados "$@"
